---
swagger: "2.0"
info:
  description: "Récupérez les informations des capteurs stockés dans la ba de données."
  version: "0.2.0"
  title: "MQTT API"
basePath: "/v1"
schemes:
- "https"
produces:
- "application/json"
paths:
  /sensors:
    get:
      summary: "Liste des capteurs recensés"
      description: "Cette entrée d'API permet de recevoir les différents capteurs."
      operationId: "sensorsGET"
      parameters:
      - name: "limit"
        in: "query"
        description: "La limite de Sensors renvoyés"
        required: false
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Un tableau de Sensor."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Sensor"
        default:
          description: "Erreur inattendue."
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Default"
  /sensors/{sensor_id}:
    get:
      summary: "Liste des mesures relevées par un capteur"
      description: "Cette entrée d'API permet d'obtenir la liste des capteurs répondant à des critères de recherche comme spécifié dans la requête"
      operationId: "sensorsSensor_idGET"
      parameters:
      - name: "sensor_id"
        in: "path"
        description: "L'id du capteur pour lequel effectuer la recherche"
        required: true
        type: "string"
      - name: "after"
        in: "query"
        description: "Les capteurs enregistrés après cette date."
        required: false
        type: "string"
        format: "date-time"
      - name: "before"
        in: "query"
        description: "Les capteurs enregistrés avant cette date."
        required: false
        type: "string"
        format: "date-time"
      - name: "limit"
        in: "query"
        description: "La limite de résultats renvoyés"
        required: false
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Un tableau de Sensor répondant aux critères de recherche."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Sensor"
        default:
          description: "Erreur inattendue."
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Default"
  /sensors/{sensor_id}/modify:
    post:
      summary: "Modifie les informations d'un capteur"
      description: "Lors de la mise en fonctionnement d'un capteur, on peut vouloir modifier ses informations dans la base de données, comme son emplacement, etc. Ce sont des données propres au capteur, qui ne dépendent pas des relevés."
      operationId: "sensorsSensor_idModifyPOST"
      parameters:
      - name: "sensor_id"
        in: "path"
        description: "L'identifiant du capteur"
        required: true
        type: "string"
      - name: "name"
        in: "query"
        description: "Le nouveau nom du capteur"
        required: false
        type: "string"
      - name: "location"
        in: "query"
        description: "La localisation du capteur"
        required: false
        type: "string"
      responses:
        200:
          description: "Le retour de la requête"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Return"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Default"
definitions:
  Sensor:
    type: "object"
    properties:
      id:
        type: "string"
        description: "Identifiant du capteur."
      name:
        type: "string"
        description: "Nom du capteur."
      location:
        type: "string"
        description: "La localisation du capteur."
      type:
        type: "string"
        description: "Le type de valeurs du capteur."
      measures:
        type: "array"
        items:
          $ref: "#/definitions/Measure"
  Measure:
    type: "object"
    properties:
      sensor_id:
        type: "string"
        description: "Identifiant du capteur rattaché"
      date:
        type: "string"
        format: "date-time"
        description: "Date à laquelle la valeur a été reçue"
      value:
        type: "string"
        description: "Valeur relevée."
  Return:
    type: "object"
    properties:
      success:
        type: "boolean"
        description: "Si l'opération s'est déroulée avec succès ou non."
      message:
        type: "string"
        description: "Message renvoyé pour décrire le déroulement de l'opération."
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"